export const AGENT_LOGIN ="AGENT_LOGIN";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const FETCH_RECENT_ORDERS = "FETCH_RECENT_ORDERS";
export const FETCH_QUICK_LINKS = "FETCH_QUICK_LINKS";
