import React, { Component } from "react";

import {
  LineChart,
  Line,
  Legend,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  ComposedChart,
  Bar
} from "recharts";

export default class OrderHistoryLineChart extends Component {
  render() {
    return (
      <ComposedChart
        width={600}
        height={300}
        data={collecteData}
        margin={{
          top: 5,
          right: 30,
          left: 20,
          bottom: 5
        }}
      >
        <XAxis dataKey="name" />
        <YAxis />
        <CartesianGrid strokeDasharray="3 3" />
        <Tooltip />
        <Legend />
        <Bar dataKey='total' barSize={20} fill='#413ea0' />
        <Line
          type="monotone"
          dataKey="total"
          stroke="#8884d8"
          activeDot={{ r: 8 }}
        />
      </ComposedChart>
    );
  }
  //<Line type="monotone" dataKey="uv" stroke="#82ca9d" />
}

var restResponse = {
  links: [
    {
      rel: "self",
      href:
        "http://busgk0711.us.oracle.com:9080/ccagentui/v1/orders?offset=0&limit=40&sort=submittedDate%3Adesc&q=state%20ne%20%22PENDING_APPROVAL_TEMPLATE%22%20AND%20state%20ne%20%22FAILED_APPROVAL_TEMPLATE%22%20AND%20state%20ne%20%22TEMPLATE%22%20AND%20state%20ne%20%22PENDING_PAYMENT_TEMPLATE%22%20AND%20state%20ne%20%22INCOMPLETE%22%20AND%20state%20ne%20%22APPROVED_TEMPLATE%22%20AND%20state%20ne%20%22BEING_AMENDED%22AND%20profileId%20eq%20%22se-570031%22AND%20siteId%20eq%20%22siteUS%22&queryFormat=SCIM&fields=items.id%2Citems.priceInfo%2Citems.payTaxInSecondaryCurrency%2Citems.payShippingInSecondaryCurrency%2Citems.secondaryCurrencyCode%2Citems.state%2Citems.priceGroupId%2Citems.siteId%2Citems.submittedDate%2Ctotal%2CtotalResults"
    },
    {
      rel: "next",
      href:
        "http://busgk0711.us.oracle.com:9080/ccagentui/v1/orders?offset=40&limit=18&sort=submittedDate%3Adesc&q=state%20ne%20%22PENDING_APPROVAL_TEMPLATE%22%20AND%20state%20ne%20%22FAILED_APPROVAL_TEMPLATE%22%20AND%20state%20ne%20%22TEMPLATE%22%20AND%20state%20ne%20%22PENDING_PAYMENT_TEMPLATE%22%20AND%20state%20ne%20%22INCOMPLETE%22%20AND%20state%20ne%20%22APPROVED_TEMPLATE%22%20AND%20state%20ne%20%22BEING_AMENDED%22AND%20profileId%20eq%20%22se-570031%22AND%20siteId%20eq%20%22siteUS%22&queryFormat=SCIM&fields=items.id%2Citems.priceInfo%2Citems.payTaxInSecondaryCurrency%2Citems.payShippingInSecondaryCurrency%2Citems.secondaryCurrencyCode%2Citems.state%2Citems.priceGroupId%2Citems.siteId%2Citems.submittedDate%2Ctotal%2CtotalResults"
    }
  ],
  total: 58,
  totalResults: 58,
  offset: 0,
  limit: 40,
  sort: [
    {
      property: "submittedDate",
      order: "desc"
    }
  ],
  items: [
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 21.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 21.99,
        total: 46.99,
        shipping: 25,
        primaryCurrencyTotal: 21.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o50425",
      state: "SUBMITTED",
      submittedDate: "2019-02-04T07:48:09.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 240.99,
        shipping: 11,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o50420",
      state: "SUBMITTED",
      submittedDate: "2019-02-01T13:25:30.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 279.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 279.98,
        total: 314.98,
        shipping: 35,
        primaryCurrencyTotal: 279.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o50417",
      state: "SUBMITTED",
      submittedDate: "2019-02-01T06:08:52.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 279.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 279.98,
        total: 314.98,
        shipping: 35,
        primaryCurrencyTotal: 279.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o50415",
      state: "SUBMITTED",
      submittedDate: "2019-02-01T05:34:07.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 229.99,
        shipping: 0,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o50413",
      state: "SUBMITTED",
      submittedDate: "2019-01-31T16:06:50.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 689.97,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 689.97,
        total: 724.97,
        shipping: 35,
        primaryCurrencyTotal: 689.97,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o50411",
      state: "SUBMITTED",
      submittedDate: "2019-01-31T15:27:41.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 264.99,
        shipping: 35,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40581",
      state: "SUBMITTED",
      submittedDate: "2019-01-26T13:03:50.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 229.99,
        shipping: 0,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40578",
      state: "SUBMITTED",
      submittedDate: "2019-01-25T11:42:05.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 229.99,
        shipping: 0,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40575",
      state: "SUBMITTED",
      submittedDate: "2019-01-25T11:40:46.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 264.99,
        shipping: 35,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40512",
      state: "SUBMITTED",
      submittedDate: "2019-01-24T15:45:20.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 264.99,
        shipping: 35,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40510",
      state: "SUBMITTED",
      submittedDate: "2019-01-24T15:43:46.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 229.99,
        shipping: 0,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40508",
      state: "SUBMITTED",
      submittedDate: "2019-01-24T15:36:10.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 229.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 229.99,
        total: 229.99,
        shipping: 0,
        primaryCurrencyTotal: 229.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40506",
      state: "SUBMITTED",
      submittedDate: "2019-01-24T15:33:32.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 459.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 459.98,
        total: 494.98,
        shipping: 35,
        primaryCurrencyTotal: 459.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o40497",
      state: "SUBMITTED",
      submittedDate: "2019-01-24T14:26:18.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 474.97,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 30.6,
        rawSubtotal: 474.97,
        total: 540.57,
        shipping: 35,
        primaryCurrencyTotal: 474.97,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o10513",
      state: "SUBMITTED",
      submittedDate: "2019-01-23T14:34:17.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 29.97,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 0,
        rawSubtotal: 29.97,
        total: 54.97,
        shipping: 25,
        primaryCurrencyTotal: 29.97,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: "defaultPriceGroup",
      siteId: "siteUS",
      id: "o10007",
      state: "SUBMITTED",
      submittedDate: "2019-01-21T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 49.95,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 4,
        rawSubtotal: 49.95,
        total: 53.95,
        shipping: 0,
        primaryCurrencyTotal: 49.95,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10041",
      state: "SUBMITTED",
      submittedDate: "2019-01-14T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 49.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 6,
        rawSubtotal: 49.99,
        total: 80.99,
        shipping: 25,
        primaryCurrencyTotal: 49.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10064",
      state: "SUBMITTED",
      submittedDate: "2019-01-14T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 110.2,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 7.8,
        tax: 11.62,
        rawSubtotal: 118,
        total: 156.82,
        shipping: 35,
        primaryCurrencyTotal: 110.2,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10042",
      state: "NO_PENDING_ACTION",
      submittedDate: "2019-01-13T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 69.9,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 6.28,
        rawSubtotal: 69.9,
        total: 84.68,
        shipping: 8.5,
        primaryCurrencyTotal: 69.9,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10065",
      state: "SUBMITTED",
      submittedDate: "2019-01-13T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 98.48,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 9.88,
        rawSubtotal: 98.48,
        total: 133.36,
        shipping: 25,
        primaryCurrencyTotal: 98.48,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10066",
      state: "SUBMITTED",
      submittedDate: "2019-01-12T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 89.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 10,
        rawSubtotal: 89.98,
        total: 134.98,
        shipping: 35,
        primaryCurrencyTotal: 89.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10043",
      state: "SUBMITTED",
      submittedDate: "2019-01-12T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 131.54,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 56.38,
        tax: 10.52,
        rawSubtotal: 187.92,
        total: 142.06,
        shipping: 0,
        primaryCurrencyTotal: 131.54,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10044",
      state: "SUBMITTED",
      submittedDate: "2019-01-11T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 24.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 2,
        rawSubtotal: 24.98,
        total: 26.98,
        shipping: 0,
        primaryCurrencyTotal: 24.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10067",
      state: "SUBMITTED",
      submittedDate: "2019-01-11T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 59.97,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 6.8,
        rawSubtotal: 59.97,
        total: 91.77,
        shipping: 25,
        primaryCurrencyTotal: 59.97,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10045",
      state: "SUBMITTED",
      submittedDate: "2019-01-10T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 147.17,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 7.75,
        tax: 14.58,
        rawSubtotal: 154.92,
        total: 196.75,
        shipping: 35,
        primaryCurrencyTotal: 147.17,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10068",
      state: "SUBMITTED",
      submittedDate: "2019-01-10T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 50,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 6.8,
        rawSubtotal: 50,
        total: 91.8,
        shipping: 35,
        primaryCurrencyTotal: 50,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10069",
      state: "SUBMITTED",
      submittedDate: "2019-01-09T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 60.99,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 5.56,
        rawSubtotal: 60.99,
        total: 75.05,
        shipping: 8.5,
        primaryCurrencyTotal: 60.99,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10046",
      state: "SUBMITTED",
      submittedDate: "2019-01-09T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 37.97,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 3.04,
        rawSubtotal: 37.97,
        total: 41.01,
        shipping: 0,
        primaryCurrencyTotal: 37.97,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10047",
      state: "SUBMITTED",
      submittedDate: "2019-01-08T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 57.97,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 2,
        tax: 4.64,
        rawSubtotal: 59.97,
        total: 62.61,
        shipping: 0,
        primaryCurrencyTotal: 57.97,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10070",
      state: "SUBMITTED",
      submittedDate: "2019-01-08T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 22.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 2,
        tax: 4.62,
        rawSubtotal: 24.98,
        total: 62.6,
        shipping: 35,
        primaryCurrencyTotal: 22.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10048",
      state: "SUBMITTED",
      submittedDate: "2019-01-07T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 59.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 6.8,
        rawSubtotal: 59.98,
        total: 91.78,
        shipping: 25,
        primaryCurrencyTotal: 59.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10071",
      state: "SUBMITTED",
      submittedDate: "2019-01-07T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 79.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 9.2,
        rawSubtotal: 79.98,
        total: 124.18,
        shipping: 35,
        primaryCurrencyTotal: 79.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10049",
      state: "SUBMITTED",
      submittedDate: "2019-01-06T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 89.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 10,
        rawSubtotal: 89.98,
        total: 134.98,
        shipping: 35,
        primaryCurrencyTotal: 89.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10072",
      state: "SUBMITTED",
      submittedDate: "2019-01-06T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 47.95,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 2,
        tax: 5.84,
        rawSubtotal: 49.95,
        total: 78.79,
        shipping: 25,
        primaryCurrencyTotal: 47.95,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10050",
      state: "SUBMITTED",
      submittedDate: "2019-01-05T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 15,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 3.2,
        rawSubtotal: 15,
        total: 43.2,
        shipping: 25,
        primaryCurrencyTotal: 15,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10051",
      state: "SUBMITTED",
      submittedDate: "2019-01-04T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 59,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 4.72,
        rawSubtotal: 59,
        total: 63.72,
        shipping: 0,
        primaryCurrencyTotal: 59,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10052",
      state: "SUBMITTED",
      submittedDate: "2019-01-03T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: false,
        secondaryCurrencyShippingAmount: 0,
        amount: 36.98,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 0,
        tax: 4.96,
        rawSubtotal: 36.98,
        total: 66.94,
        shipping: 25,
        primaryCurrencyTotal: 36.98,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10053",
      state: "SUBMITTED",
      submittedDate: "2019-01-02T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 99.68,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 5.25,
        tax: 9.98,
        rawSubtotal: 104.93,
        total: 134.66,
        shipping: 25,
        primaryCurrencyTotal: 99.68,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10054",
      state: "SUBMITTED",
      submittedDate: "2019-01-01T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    },
    {
      priceInfo: {
        secondaryCurrencyTaxAmount: 0,
        discounted: true,
        secondaryCurrencyShippingAmount: 0,
        amount: 142.43,
        secondaryCurrencyTotal: 0,
        manualAdjustmentTotal: 0,
        discountAmount: 7.5,
        tax: 15,
        rawSubtotal: 149.93,
        total: 202.43,
        shipping: 45,
        primaryCurrencyTotal: 142.43,
        amountIsFinal: false,
        currencyCode: "USD"
      },
      secondaryCurrencyCode: null,
      priceGroupId: null,
      siteId: "siteUS",
      id: "o10055",
      state: "SUBMITTED",
      submittedDate: "2018-12-31T07:53:58.000Z",
      payShippingInSecondaryCurrency: null,
      payTaxInSecondaryCurrency: null
    }
  ]
};

var collecteData = restResponse.items.map(function(order) {
  return {
    name: new Intl.DateTimeFormat("en-IND").format(
      new Date(order.submittedDate)
    ),
    total: order.priceInfo.total
  };
});

//restResponse.items
